name: Read Android Build Gradle
description: Parses android build gradle and registers values as outputs.
author: Jason Wu
inputs:
  path:
    required: false
    description: Path to your app's build.gradle
    default: app/build.gradle
  expose-version-code:
    required: true
    description: Expose version code
  expose-version-name:
    required: true
    description: Expose version name
runs:
  using: node16
  main: dist/index.js
